# Default (shared settings)
name = "underseerr-notifications"
main = "src/index.ts"
compatibility_date = "2023-10-25"

# Environment: Staging
[env.staging]
name = "underseerr-notifications-staging"
[[env.staging.kv_namespaces]]
binding = "TOKENS"
id = "" # TODO: Run `npx wrangler kv:namespace create "TOKENS" --env staging`

# Environment: Production
[env.production]
name = "underseerr-notifications-prod"
[[env.production.kv_namespaces]]
binding = "TOKENS"
id = "" # TODO: Run `npx wrangler kv:namespace create "TOKENS"` (or reuse the existing one)
