name = "underseerr-notifications"
main = "src/index.ts"
compatibility_date = "2023-10-25"

# KV Namespace binding for storing tokens
# You will need to create this namespace: npx wrangler kv:namespace create "TOKENS"
[[kv_namespaces]]
binding = "TOKENS"
id = "" # To be filled by user after creation


[vars]
# We will store the Service Account JSON here or in secrets
# GOOGLE_APPLICATION_CREDENTIALS_JSON = ""
